import { Pokemon } from "./pokemon";

export const POKEMONS : Pokemon[] = [
    {
        id: 1,
        hp: 25,
        cp: 5,
        name: 'Bulbizarre',
        picture: 'https://www.serebii.net/pokemon/art/001.png',
        types: ['Plante', 'Poisson'],
        created: new Date(),
    },
    {
        id: 2,
        hp: 28,
        cp: 6,
        name: 'Salamèche',
        picture: 'https://www.serebii.net/pokemon/art/004.png',
        types: ['Feu'],
        created: new Date(),
    },
    {
        id: 3,
        hp: 21,
        cp: 4,
        name: 'Carapuce',
        picture: 'https://www.serebii.net/pokemon/art/007.png',
        types: ['Eau'],
        created: new Date(),
    },
    {
        id: 4,
        hp: 16,
        cp: 2,
        name: 'Aspicot',
        picture: 'https://www.serebii.net/pokemon/art/007.png',
        types: ['Insecte','Poison'],
        created: new Date(),
    },
    {
        id: 5,
        hp: 30,
        cp: 7,
        name: 'Roucoule',
        picture: 'https://www.serebii.net/pokemon/art/007.png',
        types: ['Normal','Vol'],
        created: new Date(),
    },
    {
        id: 6,
        hp: 18,
        cp: 6,
        name: 'Ratata',
        picture: 'https://www.serebii.net/pokemon/art/007.png',
        types: ['Normal'],
        created: new Date(),
    },
    {
        id: 7,
        hp: 14,
        cp: 5,
        name: 'Piafabec',
        picture: 'https://www.serebii.net/pokemon/art/007.png',
        types: ['Normal','Vol'],
        created: new Date(),
    },
];